### ISSUE TITLE
Content Model Missing

### ISSUE THREAD

**Issue by mouadbouras** [randysingh/not-ubereats#1]
It would be very helpful and time saving to provide a JSON dump of the ContentModels for Restaurant and Hero. 
The project crashes on startup without. 
Thanks.

**Comment by randysingh** [comment]
Oh good point! I will try to add some mock data for development.

**Comment by mouadbouras** [comment]
Please! and thank you!  I've been having a bit of trouble getting things setup without!

**Comment by randysingh** [comment]
I've added the content models into a sample folder and updated the readme. Sorry for the delay!
